config/routes.rb
Rails.application.routes.draw do
  resources :response, only: [:show]
  resources :tickets
  
  # to DRY up code so controllers don't have to specify the path it's on
  # just call requests.path
  root to: redirect('/tickets')
end

app/models/ticket.rb
# for ease of configuration, ActiveRecord with a database was skipped
# the models here have no database
class Ticket
    attr_reader :id, :subject, :description, :created_at, :requester_id, :status
    
    def initialize(data)
        @id = data['id']
        @subject = data['subject']
        @description = data['description']
        date = DateTime.parse(data['created_at'])
        @created_at  = date.to_date if date
        @requester_id = data['requester_id'] 
        @status = data['status'] 
    end
    
    # separate model logic from controller
    def self.array(data_array)
        data_array.map {|data| Ticket.new(data) }.compact
    end
    
end

app/models/zendesk.rb
# for ease of configuration, ActiveRecord with a database was skipped
# the models here have no database

# mockable requests
class Zendesk
    
    # example usage of search params
    # json_data page: 3, per_page: 25
    def self.json_data(path, search_params)
        
        resp = api_response(path, search_params)
        
        JSON.parse resp.body
    end
    
    
    
    # encapsulating the actual response from controllers 
    private
    
    # using the http gem, we can simplify the basic auth process 
    # https://developer.zendesk.com/rest_api/docs/support/introduction#using-basic-authentication
    def self.api_response(path, search_params)
        key = Rails.configuration.api['key']
        url = Rails.configuration.api['url']
        content_type = Rails.configuration.api['content_type']
        resp = HTTP.headers(accept: content_type).auth(key).get(url + path, params: search_params)
        
        unless resp.status.success?
            raise APIRequestError if resp.status.code.between?(400, 499)
            raise APIServerError if resp.status.code >= 500
        end
        
        resp
    end
    
    
    
    
    
    class APIError < StandardError
    end
    
    class APIRequestError < APIError
        def message
          "The received API response is invalid: check your syntax, authentication etc."
        end
    end
    
    class APIServerError < APIError
        def message
          "Seems like our server is unavailable, woops :("
        end
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    API = 'api_request'
    GENERAL = 'general'
    protect_from_forgery with: :exception
    include ApplicationHelper
    
    # generally a bad idea, but this is how I interpreted the requirement
    # "Tells the user something is wrong if there is a program error."
    rescue_from StandardError, with: :program_error_render
    rescue_from Zendesk::APIError, with: :api_error_render
    
    
    def data(**search_params)
        Zendesk.json_data(request.path, search_params)
    end
    
    def api_error_render(error)
        redirect_to response_path(API), notice: error.message
    end
    
    def program_error_render(error)
        redirect_to response_path(GENERAL), notice: error.message
    end
    
    
    
end

app/controllers/response_controller.rb
class ResponseController < ApplicationController
  
  def show
    @response_type = params[:id]
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  TICKETS_PER_PAGE = 25
  
  def index
    @page = params.fetch(:page, 1).to_i
    data = data( page: @page, per_page: TICKETS_PER_PAGE)
    @tickets = Ticket.array(data['tickets'])
    
    @has_next_page = data['next_page']
    @has_prev_page = data['previous_page']
  end

  def show
    @ticket = Ticket.new(data['ticket'])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicketViewerZendesk</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/response/index.html.erb
<% if notice %>
    <h1><%= notice %></h1>
    <p>The API request failed :( </p>
<% else %>
    <h1> Everything seems fine</h1>
    <p>
        Unless you refreshed the page. Go back to the
        <%= link_to "Tickets page", tickets_path %>
    </p>
<% end%>

app/views/response/show.html.erb
<% if notice %>
    <h1><%= @response_type.capitalize %> error </h1>
    <p> <%= notice %> </p>
<% else %>
    <h1> Everything seems fine</h1>
    <p>
        Unless you refreshed the page. Go back to the
        <%= link_to "Tickets page", tickets_path %>
    </p>
<% end%>

app/views/tickets/index.html.erb
<h1>Zendesk Ticket Viewer</h1>
<h2>Tickets displayed: <%= @tickets.size %></h2>


<br>
<br>

<table>
  <thead>
    <tr>
      <th>ID </th>
      <th>Subject</th>
      <th>Created At</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.id%></td>
        <td><%= link_to ticket.subject, ticket_path(ticket.id) %></td>
        <td><%= ticket.created_at %></td>
        <td><%= ticket.status %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if @has_prev_page %>
  <%= link_to 'Prev', tickets_path(page: @page - 1) %> | 
<% end%>

<% if @has_next_page %>
  <%= link_to 'Next', tickets_path(page: @page + 1) %> 
<% end %>

app/views/tickets/show.html.erb
<p>
  <h2> <%= @ticket.subject %>:</h2>
  <%= @ticket.description %>
</p>

<p>
  Created at <%= @ticket.created_at %> 
  with requester ID <%= @ticket.requester_id %>
</p>

<p>
  <h2><%= @ticket.status.capitalize %></h2>
</p>

<%= link_to 'Back', tickets_path %>